AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Twitch-hook

  Sample SAM Template for Twitch-hook

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    MemorySize: 128
    Timeout: 15

Resources:
  TwitchScanFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: twitch_scan/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: cron(0/10 * * * ? *)
      Environment:
        Variables:
          client_id: ''
          authorization: ''
          query: ''
          TWITCH_API_STATUS: ''
          GAS_API_ENDPOINR: ''
          SLACK_WEBHOOK: ''
          SLACK_USERNAME: ''
          SLACK_ICON: ''
